version: '3'

services:
  db:
    container_name: mtr.time-tracker.database
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "mtr-time-tracker"
    user: "1000:50"
    volumes:
      - /wd/trash/timetracker:/var/lib/mysql
  web:
    container_name: mtr.time-tracker.web
    build: .
    image: mtr.time-tracker
    volumes:
      - .:/code
    ports:
      - "8888:8000"
    depends_on:
      - db
    links:
      - db
    entrypoint: ["/code/server-setup/wait-for-it.sh", "db:3306", "--timeout=30", "--", "/code/server-setup/entrypoint.sh"]