version: '3'

services:
  db:
    container_name: mtr.time-tracker.database
    image: mysql
    environment:
      MYSQL_DATABASE: 'mtr-time-tracker'
      MYSQL_USER: 'mtr-time-tracker'
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_PASS: 'password'
    user: "1000:50"
    volumes:
      - ./mysql_data:/var/lib/mysql
  web:
    container_name: mtr.time-tracker.web
    build: .
    image: mtr.time-tracker
    volumes:
      - .:/code
    ports:
      - "8888:8000"
    depends_on:
      - db
    links:
      - db
    entrypoint: ["/code/server-setup/wait-for-it.sh", "db:3306", "--timeout=30", "--", "/code/server-setup/entrypoint.sh"]